# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1545bd12b0bb0e60575db0b373e655bf369575715ad60600e0f9d66e4be094decbf3fe5ae71db514474f449fa5e24480dce2cb30709d66ac7155b7036cf3051d

test:
  secret_key_base: ec189c8e04c4c2170ef4f6d47f57dc455bb9014846fa642feb91666daa939a023be8489a23822526904a5b06b74aeea6398f9cb1c8f65081ff1c48b38d24d81f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
